### ISSUE TITLE
Incompatibility with generators

### ISSUE THREAD

**Issue by hikkyu** [strongloop/loopback-sdk-angular-cli#24]
Hello!

In my model I used a remoteMethod how use generator.

When I use lb-ng server/server.js ./lb-service.js I got this exception:

```shell
Loading LoopBack app "/pathToProject/server/server.js"
/pathToProject/common/service/moltin/product.js:12
    generatorHelper.run(function*() {
                                ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/pathToProject/common/models/product.js:3:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /pathToProject/node_modules/loopback-boot/lib/executor.js:194:20
    at Array.forEach (native)
```

Is there a way to execute this lb-ng utils with `--harmony_generators` ?

**Comment by bajtos** [comment]
Hi, you can try https://iojs.org/, it supports generators OOTB.

Another option is to explicitly start the generator script via node process:

```
$ node --harmony_generators `which lb-ng`
```

**Comment by hikkyu** [comment]
Thank's a lot for your answer :+1:
