### ISSUE TITLE
lb-ng errors on remote methods with array-based argument definitions

### ISSUE THREAD

**Issue by npedrini** [strongloop/loopback-sdk-angular-cli#31]
The `lb-ng` command fails if any exposed models contain remoteMethod definitions where at least one argument definition is an array. This seems to counter the Loopback docs which state that arrays are supported for long strings: https://docs.strongloop.com/display/public/LB/Remote+methods#Remotemethods-Argumentdescriptions

Here is the stack trace:

 ```
throw err;
  ^

TypeError: ejs:435
    433| -%>
    434| 
 >> 435| <%
    436|   if (action.internal) {
    437| -%>
    438|         // INTERNAL. <%- action.internal %>

(arg.description || "").replace is not a function
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:102:25)
    at Array.forEach (native)
    at ngdocForMethod (eval at <anonymous> (/usr/local/lib/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:101:314)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:41:92)
    at Array.forEach (native)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:40:87)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:111:50)
    at /usr/local/lib/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/usr/local/lib/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/node_modules/ejs/lib/ejs.js:293:13)
    at Object.generateServices [as services] (/usr/local/lib/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/lib/services.js:38:14)
```
Changing the offending arguments from array to string fixes the issue.

**Comment by davidcheung** [comment]
@npedrini  seems like same issue as https://github.com/strongloop/loopback-sdk-angular/issues/161,
I believe this is an issue with loopback-sdk-angular, will close this issue and reference your issue there, 
Thanks!
