### ISSUE TITLE
lb-ng not generating the services.

### ISSUE THREAD

**Issue by tinker20** [strongloop/loopback-sdk-angular-cli#39]
I am geting this error when I try to generate the lb-services with the help of lb-ng tool. This is strange because I seem to run the right command i.e, 

```
   lb-ng server/server.js client/scripts/services/lb-services.js
```

The error I am getting in the terminal is :-

 ```
TypeError: Cannot read property 'name' of undefined
    at DataSource.columnMetadata (/Users/sayan/dev/lb-app/node_modules/loopback-datasource-juggler/lib/datasource.js:1741:74)
    at DataSource.defineForeignKey (/Users/sayan/dev/lb-app/node_modules/loopback-datasource-juggler/lib/datasource.js:1818:26)
    at Function.hasMany (/Users/sayan/dev/lb-app/node_modules/loopback-datasource-juggler/lib/relation-definition.js:632:24)
    at Function.hasMany (/Users/sayan/dev/lb-app/node_modules/loopback-datasource-juggler/lib/relations.js:68:29)
    at EventEmitter.<anonymous> (/Users/sayan/dev/lb-app/node_modules/loopback-datasource-juggler/lib/datasource.js:420:37)
    at EventEmitter.g (events.js:180:16)
    at EventEmitter.emit (events.js:95:17)
    at DataSource.setupDataAccess (/Users/sayan/dev/lb-app/node_modules/loopback-datasource-juggler/lib/datasource.js:526:14)
    at DataSource.attach (/Users/sayan/dev/lb-app/node_modules/loopback-datasource-juggler/lib/datasource.js:738:8)
    at Function.ModelClass.attachTo (/Users/sayan/dev/lb-app/node_modules/loopback-datasource-juggler/lib/model-builder.js:331:16)
    at Registry.configureModel (/Users/sayan/dev/lb-app/node_modules/loopback/lib/registry.js:238:15)
    at configureModel (/Users/sayan/dev/lb-app/node_modules/loopback/lib/application.js:441:16)
    at EventEmitter.app.model (/Users/sayan/dev/lb-app/node_modules/loopback/lib/application.js:133:5)
    at /Users/sayan/dev/lb-app/node_modules/loopback-boot/lib/executor.js:186:9
    at Array.forEach (native)
    at setupModels (/Users/sayan/dev/lb-app/node_modules/loopback-boot/lib/executor.js:182:23)
    at execute (/Users/sayan/dev/lb-app/node_modules/loopback-boot/lib/executor.js:33:3)
    at bootLoopBackApp (/Users/sayan/dev/lb-app/node_modules/loopback-boot/index.js:140:3)
    at Object.<anonymous> (/Users/sayan/dev/lb-app/server/server.js:22:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Any help on this?

**Comment by kamal0808** [comment]
@tinker20 - I get the same error, any updates on this?

**Comment by lukealford** [comment]
I know this is old, but I always found I got errors if I wasn't in the root directory of the strongloop app.

**Comment by tinker20** [comment]
@kamal0808 @lukealford The plausible solution to this is to put all the lb-services related configurations in a task specified in a Gruntfile. Either wire it with the default Grunt task or with some other custom task as per your need. Then use this command to generate the ```lb-services.js```

```NODE_ENV=<env_name> DEBUG=server:middleware:security:acl​*,common:models:*​,boot:* CONNECTOR=<connector_name> DB_URL=<specify db url> grunt <task_name>```

**Comment by carlosalvarez91** [comment]
@tinker20  can you please explain how do you do that solution ? thanks

**Comment by bajtos** [comment]
Hello, is this issue still relevant?

The error message suggest that your application cannot be booted. What happens when you run the following command instead of `lb-ng`?

```
node server/server.js
```
