### ISSUE TITLE
Error lb-ng

### ISSUE THREAD

**Issue by carlosalvarez91** [strongloop/loopback-sdk-angular-cli#66]
When I try to generate lb-services at the client with lb-ng command I'm getting this error:

```
bash-3.2$ lb-ng server/server.js client/www/lib/lb-services.js
Loading LoopBack app "/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/server/server.js"

assert.js:85
throw new assert.AssertionError({
^
AssertionError: Invalid relation type: undefined
at /Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-datasource-juggler/lib/dataso
urce.js:458:7
at Array.forEach (native)
at DataSource.defineRelations (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-d
atasource-juggler/lib/datasource.js:456:28)
at DataSource.setupDataAccess (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-d
atasource-juggler/lib/datasource.js:536:8)
at DataSource.attach (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-datasource
-juggler/lib/datasource.js:753:8)
at Function.ModelClass.attachTo (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback
-datasource-juggler/lib/model-builder.js:339:16)
at Registry.configureModel (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback/lib/
registry.js:244:15)
at configureModel (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback/lib/applicati
on.js:466:16)
at EventEmitter.app.model (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback/lib/a
pplication.js:140:5)
at /Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-boot/lib/executor.js:202:9
at Array.forEach (native)
at setupModels (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-boot/lib/executo
r.js:198:23)
at execute (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-boot/lib/executor.js
:39:3)
at bootLoopBackApp (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-boot/index.j
s:154:3)
at Object. (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/server/server.js:16:1)
at Module._compile (module.js:570:32)
```
Any solution?
Thanks

**Comment by bajtos** [comment]
Hello, is this issue still relevant? Please provide us with a small application reproducing the problem - see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report
